CREATE TABLE voters (
	ID		INTEGER PRIMARY KEY,
	FIRST	TEXT,
	LAST	TEXT,
	EMAIL	TEXT
);

CREATE TABLE ballots (
	BID		INTEGER PRIMARY KEY,
	BNAME	TEXT
);

CREATE TABLE issues (
	IID		INTEGER PRIMARY KEY,
	INAME	TEXT,
	BID		INTEGER REFERENCES ballots(BID)
);

CREATE TABLE votes (
	VID		INTEGER PRIMARY KEY,
	TS		INTEGER,
	IID		INTEGER REFERENCES issues(IID),
	VOTER	INTEGER REFERENCES voters(ID),
	VOTE	TEXT
);

